### ISSUE TITLE
Hibernate Validator doesn't always work.

### ISSUE THREAD

**Issue by kevind-wgu** [avaje/avaje-http#83] opened 2022-06-01 22:51 UTC
I have noticed that when I try to use the bean validation, sometimes it compiles, sometimes it fails to compile. I occationally get this error.

```
[ERROR] ~/avaje_test2/target/generated-sources/annotations/edu/wgu/ai/service/impl/MyController$Route.java:[15,8] No dependency provided for io.avaje.http.api.Validator on edu.wgu.ai.service.impl.MyController$Route
[ERROR] Dependencies [io.avaje.http.api.Validator] are not provided - missing @Singleton, @Component, @Factory/@Bean or specify external dependency via @InjectModule requires attribute
```

In my app I do this.

```
@Valid
public class MyObj {
}

@Valid
@Controller
@Path("/path")
public class MyController {
    private final MyReadService myReadService;

    @Inject
    public MyController(MyReadService myReadService) {
        this.myReadService = myReadService;
    }

    @Post("/{id}")
    public void create(MyObj obj) {
    }
}

import io.avaje.http.api.Validator;

@InjectModule(name = "app", requires = Validator.class)
@OpenAPIDefinition(info = @Info(title = "Example service", description = "Example Javalin controllers with Java and Maven"))
public class Main {
    public static void main(String[] args) {
         Javalin app = Javalin.create(config -> {
            config.showJavalinBanner = false;
            config.addStaticFiles("public", Location.CLASSPATH);
            config.accessManager((handler, ctx, permittedRoles) -> {
                log.debug("allow access ...");
                handler.handle(ctx);
            });
          });

         BeanScope beanScope = BeanScope.builder().build();
        List<WebRoutes> webRoutes = beanScope.list(WebRoutes.class);
        app.routes(() -> webRoutes.forEach(WebRoutes::registerRoutes));

        app.start(port);
        return app;
    }
}
```

Sometimes this works, sometimes this fails. Not sure why it fails or works. Not sure how to fix it when it is failing. It is almost like something is cached somewhere.

When it is failing the only way I can get around it is add the class manually by doing this.
```
@Component
public class BeanValidation extends BeanValidator {
}
```

**Comment by rbygrave** [comment] 2022-06-02 02:41
I'm thinking this is maybe related to the version of `avaje-inject` and the version of `avaje-http-hibernate-validator` in that they need to be compatible. 

In short, check that you are using the latest of both which is `8.5` of `avaje-inject` and `2.8` of `avaje-http-hibernate-validator`.


Unfortunately I made a change to `avaje-inject` which meant updating the `avaje-http-hibernate-validator`. They should be all good if we are using the latest of both.

**Comment by rbygrave** [comment] 2022-06-07 11:01
So when I `mvn clean test` it compiles fine.  IntelliJ IDE Rebuild, reproduces the error.  

Looking closer, the mvn clean test generates a `AppModule` as expected with  `@InjectModule(requires={io.avaje.http.api.Validator.class})` ... but the IntelliJ IDE Rebuild instead produces a `ImplModule` without the `requires={io.avaje.http.api.Validator.class}`

So there seems some interesting difference there.   Ah, I think I found the issue.

```
@Scope
@InjectModule()
public @interface MyCustomScope {
}
```
Custom scopes are not supposed to have `@InjectModule` and we should really only have 1 of them.  The presence of the `@InjectModule()` here on `MyCustomScope` seems to cause the problem. Specifically I think this is making it lose the `requires={io.avaje.http.api.Validator.class}` that we want on the module.

So, remove the `@InjectModule()` from `MyCustomScope` and do a clean rebuild ... and then from then on we should be good.

We should see the `AppModule` being generated and it should have the `requires={io.avaje.http.api.Validator.class}` (and we should no longer see the ImplModule being generated).

**Comment by rbygrave** [comment] 2022-06-07 11:09
Hmmm, there is definately a bug here with IDE rebuild - the `@InjectModule` on the custom scope is messing with the `@InjectModule` of the default module.

**Comment by rbygrave** [comment] 2022-06-07 20:46
Ok, found the bug !!  It took me a couple of goes to "spot" it.

the avaje-inject-generator had code:

```java
    Set<? extends Element> elementsAnnotatedWith = roundEnv.getElementsAnnotatedWith(InjectModule.class);
    if (!elementsAnnotatedWith.isEmpty()) {
      Iterator<? extends Element> iterator = elementsAnnotatedWith.iterator();
      if (iterator.hasNext()) {
        Element element = iterator.next();
        Scope scope = element.getAnnotation(Scope.class);
        if (scope == null) {
          // it it not a custom scope annotation
          InjectModule annotation = element.getAnnotation(InjectModule.class);
          if (annotation != null) {
            defaultScope.details(annotation.name(), element);
          }
        }
      }
    }
``` 
The problem here is ... it only goes through the **_first_** element of the iterator regardless ... so IF the first element returned in this set is the custom scope it will get ignored (because the `@scope` is not null) BUT it then stops and doesn't look at any other element annotated with `@InjectModule`.  

This is why sometimes it worked and sometimes it didn't ... it depended on the **_order of the elements_** returned by `roundEnv.getElementsAnnotatedWith(InjectModule.class)` - dang !!!

The fix is to iterate ALL elements in that iterator, in fact replace the iterator with enhanced for loop.

Nice bug.  Thanks hugely for creating this little test project !!

**Comment by rbygrave** [comment] 2022-06-08 02:30
Fixed in avaje-inject version 8.6

**Comment by rbygrave** [comment] 2022-06-08 11:04
avaje-inject version 8.6 has been released.  I'll close this and reopen if necessary.

**Closed by rbygrave** 2022-06-08 11:04 UTC
Labels: bug

**Comment by kevind-wgu** [comment] 2022-06-09 14:48
Thanks for the fixes!

In your documentation you have the new `@Scope` with an `@InjectModule` on the `MyCustomScope` class under the heading "Custom scope dependencies". That is why I was adding it to my scope object. Looking at the documentation it looks like it is on purpose though.

Another question though. I have the ability to automatically use `@RequestScope` if I inject that `JavalinContext` into my controller. Is there a way to use RequestScope outside of this? For example if I want to have a service class that is recreated for every request?

**Comment by rbygrave** [comment] 2022-06-09 21:01
> documentation you have the new @Scope with an @InjectModule on the MyCustomScope 

Yes, the docs are correct. Yes you were correct to use `@Scope` with an `@InjectModule`. My comment about removing it was wrong really.  

> For example if I want to have a service class that is recreated for every request?

`@Prototype` will create a new instance each time it is requested. If a service class is "stateful", it could be a `@Prototype` but then it would need to be injected into things that are also either prototype scope or request scoped. As I see it, all service classes should be stateless and not need to be `@Prototype` - keen to here more detail on this case, the motivations for the service class to be prototype/request scope.

What makes this "request scope" special is that they need the appropriate [web framework specific] request &/or response objects injected into the controller - these are created externally to avaje-inject. In this way these "request scope beans" are always expected to be controllers (not service classes, because in  theory the web request/response objects don't get past the controller into the service classes - we are not expected to need the Javalin Context in a service class).

A alternative way to do this is via "custom scopes" (that is a more general approach):   
- We put all our request scoped things into a "custom scope" (say `@WebRequest`).
- For each request we programmatically create the custom scope passing the [Javalin Context or Helidon request/response etc]
- This scope lives only for the life of the web request
- We use a parent BeanScope that has all the things that are singleton/stateless


This approach works but it isn't ideal in the sense that it is more overhead creating a custom scope for each request relative to just invoking a factory method (BeanFactory<ControllerType, JavalinContextType>.

Not sure I've answered your question here. Let me know if this made some sense.
